### ISSUE TITLE
Unsupported Redis Commands as of 6.2.0

### ISSUE THREAD

**Issue by chayim** [redis/redis-py#1546]
The following is the list of released redis commands that redis-py does not support. This is a tracking issue, so that we can link back, and check off each item as support is added, or the decision is made to node support them. Thanks to @AvitalFineRedis for compiling this list by going through each redis command. For the curious, the full up-to-date command list can always be found [here](https://github.com/redis/redis-doc/blob/master/commands.json).

- [x] ACL DELUSER - support deletion of only one user (can't have a list of users)
- [x] ACL GENPASS - Does not support optional parameter `bits`
- [x] ACL HELP - not supported
- [x] AUTH - not supported
- [x] BGSAVE - Does not support optional parameter `SCHEDULE` (version >= 3.2.2)
- [x] CLIENT KILL - does to support `USER` filter
- [x] CLIENT LIST - support only single client-id
- [x] CLIENT GETREDIR - [PR](https://github.com/redis/redis-py/pull/1623)
- [x] CLIENT PAUSE - #1549 (need to add test)
- [x] CLIENT REPLY - not supported
- [x] CLIENT TRACKING - #1612 
- [x] CLIENT TRACKINGINFO- not supported
- [x] COMMAND (get an array of Redis commands details) - not supported
- [x] COMMAND COUNT  - not supported
- [x] COMMAND GETKEYS - #1738
- [x] COMMAND INFO  - #1609 
- [x] DEBUG SEGFAULT - not supported
- [x] DISCARD - not supported
- [x] FAILOVER - not supported (version >= 6.2.0)
- [x] GEOADD - [NX|XX] [CH] options not supported (version >= 6.2.0) #1605
- [x] GEORADIUS and GEORADIUSBYMEMBER -  The `ANY` option for `COUNT` is not supported #1606
- [x] GEOSEARCH
- [x] GEOSEARCHSTORE
- [x] HELLO - not supported
- [x] LULWUT - #1568 
- [x] LPUSHX - cant have a list.
- [x] MEMORY DOCTOR-  #1608
- [x] MEMORY HELP- #1608 
- [x] MEMORY MALLOC-STATS- not supported
- [x] MIGRATE - `AUTH2` not supported #1616
- [x] MODULE LOAD - args option not supported
- [x] QUIT- not supported
- [x] RESET- not supported
- [x] RESTORE - does not support `IDLETIME` and `FREQ` params
- [x] ROLE- not supported #1610 
- [x] SCRIPT DEBUG - not supported
- [x] SCRIPT FLUSH - ASYNC flushing mode is not supported
- [x] SELECT - not supported #1825 
- [x] SET - `PXAT` and `EXAT` ar not supported.
- [x] SMISMEMBER - [PR](https://github.com/andymccurdy/redis-py/pull/1486/)
- [x] REPLICAOF - [PR](https://github.com/redis/redis-py/pull/1622)
- [x] STRALGO LCS - [PR](https://github.com/andymccurdy/redis-py/pull/1528)
- [x] SYNC and PSYNC - #1741
- [x] ZRANGESTORE and ZRANGE- `BYSCORE`, `BYLEX`, `REV` and `LIMIT` are not supported #1603
- [x] ZMSCORE - [PR](https://github.com/andymccurdy/redis-py/pull/1437)
- [x] XADD - `MINID` and `LIMIT` are not supported.
- [x] XGROUP - `CREATECONSUMER` is not supported
- [x] #1963
- [x] #1964 
- [x] #1966 
- [x] #1968
- [x] #1969
- [x] #1970
- [x] #1971
- [x] #1972
- [x] #1973
- [x] #1974 
- [x] #1975
- [x] #1976 
- [x] #1977 
- [x] #1978
- [x] #1979
- [x] #1980
- [x] #1981
- [x] #1982
- [x] #1944

**Comment by AvitalFineRedis** [comment]
[ZINTERCARD](https://redis.io/commands/zintercard) is available since 7.0.0.

**Comment by leonpros** [comment]
Support for Zset (ZRANGE) command

**Comment by chayim** [comment]
@leonpros There is no ZSET command. ZRANGE is currently supported, and the extensions we believe are missing are documented above. Are there other parts of the ZRANGE command you think we're missing?

**Comment by leonpros** [comment]
> @leonpros There is no ZSET command. ZRANGE is currently supported, and the extensions we believe are missing are documented above. Are there other parts of the ZRANGE command you think we're missing?

In the documentation above, ZRANGE is unchecked, thus i thought it was missing. Also, the is no documentation on how to use it in robot framework

**Comment by chayim** [comment]
This project definitely wouldn't document how to use it with [robot](https://robotframework.org/), but the functions themselves would be documented. The current implementation of ZRANGE is in [master](https://github.com/andymccurdy/redis-py/blob/master/redis/commands.py#L2370) and will be in the upcoming release. This is a tracking issue for missing redis commands and features. The items mentioned above, are to be added - though I don't yet know when.
