### ISSUE TITLE
Add RESP3 protocol support

### ISSUE THREAD

**Issue by uglide** [redis/redis-py#2565]
**Version**:  4.4.2
**Platform**: Any
**Description**: redis-py doesn't support RESP3 protocol.

- [ ] Add protocol option to the connection
  * [x] #2643
  * [x] #2644
  *  [x] #2645
  *  [x] #2646
  *  [x] Connection
  *  [x] Cluster Connection
  *  [x] #2647
  *  [x] SSL Connection
  *  [x] #2648
  *  [x] #2649
- [x] Refactor parsers to make it easier to add support to more protocols

- [x] Add the RESP3 parsers
   *  [x] RESP3 parse_response
   * [x] Response callbacks to RESP3
   * [x] Explore improvement sync and async parsers
   * [x] #2651
   * [x] #2652
- [x] #2653
- [ ] #2654
- [ ] #2655
- [ ] #2656

**Comment by chayim** [comment]
https://github.com/redis/redis-specifications/pull/12

**Comment by dvora-h** [comment]
- [ ] Refactor parsers to make it easier to add support to more protocols
- [ ] Add protocol option to the connection
       - [ ] Async Connection
       - [ ] Async Cluster Connection
       - [ ] Async Unix Connection
       - [ ] Async SSL Connection
       - [ ] Connection
       - [ ] Cluster Connection
       - [ ] Unix Connection
       - [ ] SSL Connection
- [ ] Add examples
- [ ] Update README
- [ ] Add the RESP3 parsers:
       - [ ] RESP3 parse_response
       - [ ] Response callbacks to RESP3
       - [ ] Explore improvement sync and async parsers
       - [ ] Clean up parser helpers functions
- [ ] Add test env for RESP3 specifically

**Comment by chayim** [comment]
Nice to have:

- [ ] Migrate tests to classes

**Comment by chayim** [comment]
Closing as cleanup, released.
